viscommunityweb/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.contrib.auth import views as auth_views
from registration.forms import RegistrationFormUniqueEmail

handler500 = 'web.views.server_error'

admin.autodiscover()
urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'viscommunityweb.views.home', name='home'),
                       # url(r'^viscommunityweb/', include('viscommunityweb.foo.urls')),

                       # Uncomment the admin/doc line below to enable admin documentation:
                       # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),


                       url(r'^accounts/register/$', 'registration.views.register',
                           {'form_class': RegistrationFormUniqueEmail,
                            'backend': 'registration.backends.default.DefaultBackend'},
                           name='registration_register'),
                       url(r'^accounts/', include('registration.backends.default.urls')),
                       url(r'^about/', 'web.views.about', name='about'),
					   url(r'^faq/', 'web.views.faq', name='faq'),

                       url(r'^profiles/', include('profiles.urls'), name='profiles'),

                       url(r'^$', 'web.views.index', name='community-home'),
                       url(r'^accounts/profile', 'web.views.profile', name='profile'),
                       url(r'^profile/(\w+)', 'web.views.public_profile', name='pub_profile'),


                       url(r'^taxonomy/add/$', 'web.views.taxonomy_add', name='add_taxonomy'),
                       url(r'^taxonomy/add/action/$', 'web.views.taxonomy_add_action', name='add_taxonomy_action'),
                       url(r'^taxonomy/edit/(?P<taxonomy_id>\d+)/$', 'web.views.taxonomy_edit', name='edit_taxonomy'),
                       url(r'^taxonomy/edit/action/$', 'web.views.taxonomy_edit_action', name='edit_taxonomy_action'),

                       url(r'^reference/add/file$', 'web.views.reference_add_upload_file', name='upload_bibtex'),
                       url(r'^reference/add/text$', 'web.views.reference_add_upload_text', name='upload_bibtex_text'),
                       url(r'^reference/edit/(?P<taxonomy_id>\d+)/(?P<reference_id>\w+)/$', 'web.views.reference_edit', name='reference_edit'),
                       url(r'^reference/json/(?P<taxonomy_id>\d+)/(?P<reference_id>\w+)/$', 'web.views.reference_json', name='reference_json'),

                       url(r'^reference/remove/(?P<taxonomy_id>\d+)/(?P<reference_id>\w+)/$',
                           'web.views.reference_remove', name='remove_reference'),
                       url(r'^reference/delete/(?P<taxonomy_id>\d+)/(?P<reference_id>\w+)/$',
                           'web.views.reference_delete', name='delete_reference'),


                       #url(r'^reference/(?P<reference_id>\w+)/$', 'web.views.reference_detail',name='reference_detail'),
                       url(r'^reference/(?P<taxonomy_id>\d+)/(?P<reference_id>\w+)/$', 'web.views.reference_detail',
                           name='reference_detail'),

                       url(r'^taxonomy/$', 'web.views.taxonomy', name='taxonomy'),
                       url(r'^taxonomy_alpha/$', 'web.views.taxonomy_alpha', name='taxonomy_alpha'),
                       url(r'^taxonomy/(?P<taxonomy_id>\d+)/$', 'web.views.taxonomy_detail', name='taxonomy_detail'),
                       url(r'^taxonomy/download/(\d+)/$', 'web.views.taxonomy_download', name='taxonomy_download'),
                       url(r'^taxonomy/delete/(\d+)/$', 'web.views.taxonomy_delete', name='taxonomy_delete'),
                       url(r'^taxonomy/split/(\d+)/$', 'web.views.taxonomy_split', name='taxonomy_download'),
                       url(r'^taxonomy/add_child/(\d+)/$', 'web.views.taxonomy_add_child', name='taxonomy_add_child'),
                       url(r'^taxonomy/add_leaf/(\d+)/$', 'web.views.taxonomy_add_leaf', name='taxonomy_add_leaf'),
                       url(r'^taxonomy/move/(\d+)/$', 'web.views.moveTaxonomyItem', name='taxonomy_move'),
                       url(r'^taxonomy/move-references/$', 'web.views.moveReferences', name='taxonomy_move'),

                       url(r'^category/rename/(?P<category_id>\d+)/', 'web.views.renameTaxonomyCategoryAPI',
                           name='category_rename'),
                       url(r'^category/delete/(?P<category_id>\d+)/', 'web.views.deleteTaxonomyCategory',
                           name='category_delete'),

                       url(r'^request_ownership/(?P<taxonomy_id>\d+)$', 'web.views.request_ownership_send',
                           name='request_ownership'),
                       url(r'^request_ownership/response/(?P<approval_id>\d+)$', 'web.views.request_ownership_response',
                           name='request_ownership_response'),
                       url(r'^revoke_ownership/(?P<taxonomy_id>\d+)$', 'web.views.revoke_ownership',
                           name='revoke_ownership'),

                       url(r'^enquiry/(?P<taxonomy_id>\d+)/$', 'web.views.handleTaxonomyEnquiry', name='enquiry'),
                       url(r'^enquiry/(?P<taxonomy_id>\d+)/(?P<reference_id>\w+)/$', 'web.views.handleReferenceEnquiry',
                           name='enquiry_reference'),
                       url(r'^enquiry/(?P<decision>\w+)/(?P<enquiry_id>\d+)/$', 'web.views.respondToTaxonomyEnquiry',
                           name='enquiry_decision'),

                       url(r'^contact/$', 'web.views.contact', name='contact'),
                       url(r'^contact/send', 'web.views.contact_send', name='contact_send'),

                       url(r'^api/taxonomyTree/(?P<formatting>\w+)', 'web.views.getTaxonomyTree',
                           name='api_taxonomy_tree'),
                       url(r'^api/taxonomyCategories', 'web.views.getTaxonomyCategories',
                           name='api_taxonomy_categories'),
                       url(r'^api/taxonomy/info/(?P<taxonomy_id>\d+)/$', 'web.views.getTaxonomyCategoryJSON',
                           name='api_taxonomy_details'),
                       url(r'^api/category/info/(?P<category_id>\d+)/$', 'web.views.getTaxonomyCategoryInformationJSON',
                           name='api_taxonomy_category_details'),

                       url(r'^account/$', 'web.views.account', name='account'),
                       url(r'^orcid$', 'web.views.orcid_profile', name='orcid'),

                       url(r'^volunteer$', 'web.views.volunteer', name='volunteer'),

                       url(r'^admin/', include(admin.site.urls), name='admin'),

                       # Static pages - e.g. about
                       url('^pages/', include('django.contrib.flatpages.urls')),
)

web/models.py
"""
 Data models
"""
from collections import defaultdict
from django.contrib.auth.models import User
from django.db import models
import user
import uuid
import hashlib
from datetime import datetime
from couchdb import *
import json

server = Server("http://127.0.0.1:5984/")

class TaxonomyArea(models.Model):
	name = models.CharField(max_length=128)
	def __unicode__(self):
		return self.name

class TaxonomyCategory(models.Model):
	class Meta:
		permissions = (
			('modify_taxonomy_categories','Modify a taxonomy category'),
		)
	name = models.CharField(max_length=128)
	area = models.ForeignKey(TaxonomyArea, null=True, blank=True)
	parent = models.ForeignKey('self', blank=True, null=True)

	def __unicode__(self):
		return self.name

class TaxonomyItem(models.Model):
	class Meta:
		permissions = (
			('modify_taxonomy_items','Create/modify a taxonomy item, including changing its category and metadata'),
			('revoke_ownership','Ability to revoke another user\'s taxonomy item ownership')
		)

	name = models.CharField(max_length=256)
	category = models.ForeignKey(TaxonomyCategory)
	detail = models.TextField(default="")
	last_updated = models.DateTimeField(auto_now=True)
	last_updated_by = models.ForeignKey(User, null=True)
	owners = models.ManyToManyField(User, related_name="owners+")

	def int_pk(self):
		try:
			return self.pk[0]
		except:
			return self.pk

	def reference_family(self):
		return ReferenceFamily(self.int_pk())

	def references(self, sort=None, reverse=False):
		return ReferenceFamily(self.int_pk()).get_references(sort,reverse)

	def remove_reference(self, ref_id):
		ReferenceFamily(self.int_pk()).remove_reference(ref_id)

	def short_description(self):
		return self.detail[:50] + '...'

	def __unicode__(self):
		return self.name + " (" + self.category.name + ")"


# reference Family - one per TaxonomyItem (as identified by its id)
class ReferenceFamily(object):
	# initialise a reference family for a taxonomy id
	def __init__(self, tax_id):
		self.db = None
		self.tax_id = str(tax_id)
		self._ensure_exists()

	# name of this database object
	def database_id(self):
		return "ref_fam_%s" % self.tax_id

	def copy_reference(self, ref_id):
		new_id = uuid.uuid4().hex
		new_rev = self.db.copy(ref_id, new_id)
		return new_id

	def move_all_references(self, new_family):
		for ref_id, rec_doc in self.get_references():
			self.move_reference(ref_id, new_family)

	def move_reference(self, ref_id, new_family):
		new_family.add_reference(self.db[ref_id])
		self.db.purge([self.db[ref_id]])

	# add a reference to this reference family
	def add_reference(self, ref):
		doc_id, rev_id = self.db.save(ref)
		# Django doesn't like Couch's _id so we'll create a redundant id attribute
		doc = self.db[doc_id]
		doc['id'] = doc_id
		self.db.save(doc)
		return doc_id

	def save_reference(self, doc):
		return self.db.save(doc)

	# get a reference by id
	def get_reference(self, ref_id):
		return self.db[ref_id]

	def delete_reference(self, ref_id):
		return self.db.delete(self.db[ref_id])

	# get all references
	def get_references(self, sort=None, reverse=False):
		emit = "emit(d._id,d)"
		if sort is not None:
			emit = "emit(d.%s,d)" % sort

		return [(x.key, x.value) for x in self.db.query("function(d) { " + emit + "; }",descending=reverse)]

	def get_references_as_dict(self, sort=None):
		refs = self.get_references()
		d = defaultdict(list)
		for k, v in refs:
			d[k] = v
		return d.items()

	def create_reference(self):
		ref_id = self.db.create({})
		return self.db[ref_id]

	# remove a reference by id
	def remove_reference(self, ref_id):
		self.db.delete(self.get_reference(ref_id))

	def remove_all_references(self):
		all_refs = self.get_references()
		for k, v in all_refs:
			self.delete_reference(k)

	# ensures db object exists; creates if not
	def _ensure_exists(self):
		try:
			self.db = server[self.database_id()]
		except:
			print "Creating database %s" % self.database_id()
			self.db = server.create(self.database_id())
			self.db.commit()
		assert (self.db is not None)

# functions for dealing with references without worrying about which taxonomy they're attached to (ehh...)
class ReferenceGlobal(object):
	def __init__(self):
		self.all_tax_ids = [x.id for x in list(TaxonomyItem.objects.all())]

	def get_reference(self, tax_id, ref_id):
		return ReferenceFamily(tax_id).get_reference(ref_id)

	def create_reference(self, tax_id):
		return ReferenceFamily(tax_id).create_reference()

	def remove_reference(self, tax_id, ref_id):
		return ReferenceFamily(tax_id).remove_reference(ref_id)
	
	def tax_items_featuring_ref(self, ref_id):
		tax_ids = []
		for tax_id in self.all_tax_ids:
			try:
				tax_ids.append(ReferenceFamily(tax_id).get_reference(ref_id))
			except:
				pass
		return tax_ids

# represents a fixed-size queue of recent reference entries
class ReferenceQueue(ReferenceFamily):
	def __init__(self, size):
		super(ReferenceQueue, self).__init__(0)
		self.queue_size = size

	def database_id(self):
		return "ref_recent"

	def add_reference(self, ref, ref_id, tax_id):
		ref['ref_doc_id'] = ref_id
		ref['tax_id'] = tax_id
		super(ReferenceQueue, self).add_reference(ref)
		self.limit_queue()

	def limit_queue(self):
		docs = self.db.query("function(d) { emit(d.id); }", descending=True, skip=self.queue_size)
		for item in docs:
			print item
			self.db.delete(self.db[item.id])


class UserProfile(models.Model):
	user = models.ForeignKey(User, unique=True)
	orcid = models.CharField(max_length=19, blank=True)
	gravatarEmail = models.CharField(max_length=100, blank=True)

	def __unicode__(self):
		return user

	def get_absolute_url(self):
		return 'profiles_profile_detail', (), {'username': self.user.username}

	get_absolute_url = models.permalink(get_absolute_url)

class OwnershipRequest(models.Model):
	class Meta:
		permissions = (
			('respond_to_ownership_requests','Can authorise/deny ownership requests'),
			('view_ownership_requests','Can view existing ownership requests'),
			('view_historical_ownership_requests','Can view all ownership requests, current and historical'),
		)

	requester = models.ForeignKey(User)
	taxonomyItem = models.ForeignKey(TaxonomyItem)
	additionalNotes = models.TextField()
	answered = models.BooleanField(default=False)

	def __unicode__(self):
		return self.requester.username + ' - ' + self.taxonomyItem.name


class Enquiry(models.Model):
	requester = models.ForeignKey(User)
	taxonomyItem = models.ForeignKey(TaxonomyItem)
	enquiry_type = models.CharField(max_length=256, default="")
	additionalNotes = models.TextField()

# front page recent references
recent_references = ReferenceQueue(3)

web/templates/base.html
<!DOCTYPE html>

<html lang="en">
<head>
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}bootstrap/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{{ STATIC_URL }}bootstrap/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="{{ STATIC_URL }}css/style.css"/>

    {% block head_additional %} {% endblock %}
    <title>{% block title %}Community-driven Visualization Resource Website{% endblock %}</title>
    <style>
        a {
            color: #ED9C28;
        }
    </style>
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                    m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-41812283-1', 'ox.ac.uk');
        ga('send', 'pageview');

        $(document).ready(function () {
            jQuery.extend({
                parseQuerystring: function () {
                    var nvpair = {};
                    var qs = window.location.search.replace('?', '');
                    var pairs = qs.split('&');
                    $.each(pairs, function (i, v) {
                        var pair = v.split('=');
                        nvpair[pair[0]] = pair[1];
                    });
                    return nvpair;
                }
            })
        });

        // for use in javascript files
        var globalURLPrefix = "{{ URL_PREPENDER }}";
        if (globalURLPrefix.charAt(globalURLPrefix.length - 1) != '/')
            globalURLPrefix += '/';
        console.log("Global URL prefix " + globalURLPrefix);
    </script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/validation.js"></script>
</head>

<body {% block body_attributes %}{% endblock %}>
<div class="topbar">
    <div class="topbar-content" align="center">
        <a href="{{ URL_PREPENDER }}/">
            <div class="logo">Home</div>
        </a>

        <div class="user-account">
            {% if user.is_authenticated %}

                <a href="{{ URL_PREPENDER }}/accounts/profile" alt="{{ user.username }}'s Profile"
                   class="btn btn-mini btn-warning"><i
                        class="glyphicon-user glyphicon"></i></a>
                <a href="{{ URL_PREPENDER }}/accounts/logout" alt="Log out" class="btn btn-mini btn-warning"><i
                        class="glyphicon-log-out glyphicon"></i></a>
            {% else %}
                <a href="{{ URL_PREPENDER }}/accounts/register" class="btn btn-default"><i
                        class="glyphicon glyphicon-check"></i> Register</a>
                <a href="{{ URL_PREPENDER }}/accounts/login" class="btn btn-default"><i
                        class="glyphicon glyphicon-log-in"></i>
                    Log In</a>
            {% endif %}

        </div>

        {% comment %}
		<div class="search" style="margin-right:20px"> #}
            <form id="search" action="{{ URL_PREPENDER }}/search" onsubmit="return validateSearchInput('search')">
			  <input id="search-text" style="width:80%" type="text" name="q" placeholder="Search References">
            </form>
		</div>
		{% endcomment %}

        <div class="menu">
            <a href="{{ URL_PREPENDER }}/taxonomy" class="menu-item">
                <img src="{{ STATIC_URL }}img/static_img/home/menu-taxonomy.png"/>

            </a>

            <a href="{{ URL_PREPENDER }}/taxonomy_alpha" class="menu-item">
                <img src="{{ STATIC_URL }}img/static_img/home/index-menu-item.png"/>

            </a>

            <a href="{{ URL_PREPENDER }}/contact" class="menu-item">
                <img src="{{ STATIC_URL }}img/static_img/home/contact.png"/>
            </a>
        </div>


    </div>
</div>

<div class="container content">

    {% block content %}{% endblock %}

</div>


<div id="footer">
    <div class="upper_footer">
        <div class="footer_container">
            <h4 id="additionalLinks">Additional BioSharing Links</h4>

            <ul class="footer_links" style="width:100px">
            </ul>
            <ul class="footer_links" style="width:200px">
                <h4>Contribute</h4>
                <li><a href="{{ URL_PREPENDER }}/about" target="_blank">About us</a></li>
                <li><a href="{{ URL_PREPENDER }}/faq/" target="_blank">FAQ</a></li>
                <li><a href="{{ URL_PREPENDER }}/contact" target="_blank">Contact us</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{{ URL_PREPENDER }}/volunteer" target="_blank">Volunteer</a></li>
                {% endif %}
                <li><a href="https://github.com/OVii/communityvisweb/issues?state=open" target="_blank">Report an
                    issue</a>
                </li>
            </ul>


            <ul class="footer_links" style="width: 200px">
                <h4>Infrastructure Information</h4>
                <li><a href="http://www.oerc.ox.ac.uk" target="_blank">Oxford e-Research Centre</a></li>
                <li><a href="http://www.ovii.org" target="_blank">OVii</a></li>

                <li><a href="https://www.github.com/ovii/communityvisweb" target="_blank">GitHub Repository</a></li>
            </ul>
        </div>
    </div>

    <div class="bottom_footer">
        <div class="footer_container">
            <br/>

            <div class="additional-information" align="center">

                © Community Resources: Visualization 2013-Present | Licensed under <a
                    href="http://creativecommons.org/licenses/by/3.0/" alt="View License" target="_blank">Creative
                Commons by 3.0 Unported</a> | Designed by <a href="http://www.antarctic-design.co.uk" target="_blank">Antarctic
                Design</a>

            </div>
        </div>
    </div>

</div>

{% block end_additional %}
{% endblock %}

</body>
</html>

web/templates/contact.html
{% extends "base.html" %}
{% load webdesign %}

{% block title %}Contact us{% endblock %}

{% block head_additional %}
    <script type="text/javascript">
        function validate() {
            var name = document.forms["contact-form"]["name"].value;
            var email = document.forms["contact-form"]["email"].value;
            var comments = document.forms["contact-form"]["comments"].value;

            blankName = (name === "");
            blankEmail = (email === "");
            blankDetails = (comments === "");

            var errorHTML = "";

            if (blankName) {
                errorHTML += '<div class="alert alert-error">Please enter a name!</div>'
            }
            if (blankEmail) {
                errorHTML += '<div class="alert alert-error">Please enter your email address!</div>'
            }
            if (blankDetails) {
                errorHTML += '<div class="alert alert-error">Please enter a message!</div>'
            }

            $("#errors").html(errorHTML);

            $("#name_group").toggleClass("form-group error", blankName);
            $("#name_help").toggleClass("hide", !blankName);

            $("#email_group").toggleClass("form-group error", blankEmail);
            $("#email_help").toggleClass("hide", !blankEmail);

            $("#comments_group").toggleClass("form-group error", blankDetails);
            $("#description_help").toggleClass("hide", !blankDetails);

            return !(blankName || blankEmail || blankDetails);

        }
    </script>


{% endblock %}

{% block content %}
	<div class="page-header">
		<h1><small><span class="glyphicon-envelope glyphicon glyphicon-pad"></span> Contact us</small></h1>
	</div>

    <div>
        {% if error_message %}
            <div class="alert alert-error">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <strong>Warning!</strong> {{ error_message }}
            </div>
        {% endif %}

        {% if success_message %}
            <div class="alert alert-success">{{ success_message }}
            </div>{% endif %}

    </div>

    <div id="login" class="login_form">

        <form action="{{ URL_PREPENDER }}/contact/send" method="post" id="contact-form" class="form-horizontal" style="margin-top:20px"
              onsubmit="return validate();" role="form">

            <div id="errors">
            </div>
            {% csrf_token %}

            <div id="name_group" class="form-group">
				<label for="name" class="col-lg-4 control-label">Name</label>
                <div class="col-lg-8">
                    <input id="name" type="text" name="name" class="form-control" value="{% if request.user.is_authenticated %}{{ request.user.username }}{% endif %}">
                </div>
            </div>
            <div id="email_group" class="form-group">
                <label for="email" class="col-lg-4 control-label">Email Address</label>
				<div class="col-lg-8">
	                <input id="email" type="email" name="email" class="form-control" value="{% if request.user.is_authenticated %}{{ request.user.email }}{% endif %}">
				</div>
            </div>

            <div id="comments_group" class="form-group">
                <label for="comments" class="col-lg-4 control-label">Comments</label>

                <div class="col-lg-8">
                    <textarea id="comments" name="comments" maxlength="5000" rows=10 class="form-control">{% if taxonomy %}I
                        wish to take
                        ownership of taxonomy item "{{ taxonomy.name }}". I include relevant details of my expertise in
                        the area.
                    {% endif %}</textarea>
                </div>
            </div>
            <div class="form-group">
                <div class="col-lg-offset-4 col-lg-8">
                    <input type="submit" class="btn btn-warning" value="Submit">
                </div>
            </div>
        </form>
    </div>

{% endblock %}

web/templates/infopage.html
{% extends 'base.html' %}

{% block content %}
    <br/>
    <div class="hero-unit">
        <h4>{{ messageTitle }}</h4>
        <p>{{ messageBody }}</p>
    </div>
{% endblock %}

web/templates/references.html
{% extends "base.html" %}

{% block title %}Visualization References{% endblock %}

{% block content %}

<h1>References</h1>


{% include "templates/references_include.html" %}

{% endblock %}

web/templates/search.html
{% extends "base.html" %}
{% block title %}Search{% endblock %}
{% block content %}

    <div class="home-content">
        <div class="row-fluid">
            <div class="search-wrapper">
                <form id="search-search" action="{{ URL_PREPENDER }}/search"
                      onsubmit="return validateSearchInput('search-search')">
                    <input id="search-text" type="text" name="q" placeholder="Search">
                </form>
            </div
        </div>

        <div class="clearfix"></div>

        <div class="hero-unit">
            <p>You searched for <strong>{{ searchTerm }}</strong>. There are <strong>{{ size }}</strong> results!</p>
        </div>


        {% for reference in searchResults %}
            <div class="reference_box">

                <p class="title"><a
                        href="{{ URL_PREPENDER }}/reference/{{ reference.id }}?currentPage={{ request.get_full_path }}">{{ reference.title }}</a>
                </p>

                <p class="authors">{{ reference.authors }}</p>

                <p><span class="journal">{{ reference.journal }}</span>{% if reference.year > 0 %}
                    <span class="year">{% if reference.journal %}
                        , {% endif %}{{ reference.year }}</span>{% endif %} </p>


            <span style="font-size: 0.8em; color:#666666">in
                {% for taxonomyItem in reference.taxonomyitem_set.all %}
                    <a href="{{ URL_PREPENDER }}taxonomy/{{ taxonomyItem.id }}"
                       style="font-size: 0.8em; color:#666666">{{ taxonomyItem.name }}</a>
                    {% if not forloop.last %}, {% endif %}
                {% endfor %}
                            </span>

                {% if reference.url %}
                    <a href="{{ reference.url }}" target="_blank" class="btn btn-mini">Read Paper</a>
                {% endif %}

                {% if not forloop.last %}
                    <hr/>
                {% endif %}

            </div>
        {% endfor %}


    </div>


{% endblock %}

web/templates/taxonomy-header.html
    <div class="page-header">
        <h1>
            <small><a href="{{ URL_PREPENDER }}/taxonomy">Taxonomy</a>
            </small>

                    <div class="btn-group pull-right">
                        <a class="btn btn-default dropdown-toggle" data-toggle="dropdown" href="#">
                            View Preference
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ URL_PREPENDER }}/taxonomy_alpha">Index</a></li>
                            <li><a href="{{ URL_PREPENDER }}/taxonomy">Taxonomy</a></li>
                        </ul>
                    </div>

        </h1>
    </div>